# Dependance

In [7]:
import numpy;

In [8]:
FLOAT = lambda x: float(x)

In [5]:
class Scanner:
  def __init__(self, type):
    self.type = type
    self.tokens = None;

  def scan(self, content):
    return {
        'csv': lambda x: self.scanCSV(x)
    }[self.type](content)
    
  def scanCSV(self, content):
    lines = content.split()
    items = []

    for line in lines:  
      items.append( line.split(',') )

    tokens = numpy.array(items)
    return tokens


In [54]:
class Parser:
  def __init__(self, methods):
    self.methods = methods
  
  def parse(self, slices):
    methods = self.methods
    items = []

    for i in range( len(methods) ):
      method = methods[i]
      matrix = numpy.array(slices[i]).transpose()

      for row in matrix:
        newrow = list( map(lambda x: method(x), row) )
        items.append( newrow )

    datas = numpy.array(items).transpose()
    return datas

# Iris
- number
- data 
- target
- feature: 4
- label: 1
- types: Setosa, Versicolour, Virginica

In [56]:
class Iris:
  def __init__(self, content):
    tokens = Scanner('csv').scan(content);

    types = list( dict.fromkeys(tokens[:, 4]) )

    data = Parser([
      FLOAT
    ]).parse([
      tokens[:, 0:4]
    ])
    
    target = Parser([
      lambda x: types.index(x)
    ]).parse([
      tokens[:, 4:5]
    ])

    self.data = data
    self.target = target
    self.types = types
    self.number = len(self.data)
    self.feature = len(data[0])
    self.label = len(target[0])

In [62]:
content = "\
5.1,3.5,1.4,0.2,Iris-setosa\n\
4.9,3.0,1.4,0.2,Iris-setosa\n\
4.7,3.2,1.3,0.2,Iris-setosa\n\
4.6,3.1,1.5,0.2,Iris-setosa\n\
5.6,3.0,4.1,1.3,Iris-versicolor\n\
5.0,3.6,1.4,0.2,Iris-setosa\n\
"

iris = Iris(content)
print(iris.data)
print(iris.target)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.6 3.  4.1 1.3]
 [5.  3.6 1.4 0.2]]
[[0]
 [0]
 [0]
 [0]
 [1]
 [0]]


# Imagenet

Imagenet是一個大型的Datasets，有超過1500萬的影像，類別超過22000。  

有分 Training Set, Validation Set, Testing Set

# MNest

# CIFAR-10

# Waveform

# WDBC